from routes import Route

OUTFILE = 'wedding_path.geojson'
MAP_FILES = '__map_files'

past = [
    'Copley Ave and Idaho St, San Diego, CA 92116',
    'Lake Murray Blvd and Mono Lake Dr, San Diego, CA 92119',
    'Cowles Mtn Blvd and Rainswept Way, San Diego, CA 92119',
    'Val Sereno Dr, Encinitas, CA',
    'North Italia, El Segundo, CA',
    'Pier Santa Barbara',
    'Santa Barbara Sunrise Rv Park',
    'Piedras Blancas Light Station',
    'Ventana Big Sur',
    '62 Point Lobos, Carmel-By-The-Sea, CA 93923',
    '1212 Forest Ave, Pacific Grove, CA',
    'Asilomar State Beach, Sunset Dr, Pacific Grove, CA',
    'Heart Shaped Rock-Love Rock, Ocean View Blvd, Pacific Grove, CA 93950',
    'Alvarado street brewing, Monterey, CA',
    'Marlow mercedes werks, Seaside, CA',
    'Las Cumbres Rd, CA 95033',
    'Eureka, Mountain View, CA',
    'Las Cumbres Rd, CA 95033',
    'San Gregorio State Beach, 20063 Cabrillo Hwy S, San Gregorio, CA 94074',
    'Jettywave Distillery, Half Moon Bay, CA',
    'San Mateo-Hayward Bridge, Foster City, CA',
    'Dimond Slice Pizza, 2208 MacArthur Blvd, Oakland, CA 94602',
    'Muth Dr, Orinda, CA',
    'Dimond Slice Pizza, 2208 MacArthur Blvd, Oakland, CA 94602',
    'Claremont Club & Spa, Berkeley, CA',
    'Dimond Slice Pizza, 2208 MacArthur Blvd, Oakland, CA 94602',
    'Balboa Ave and 26th Ave, San Francisco, CA',
    'Bolinas Beach, Unnamed Road, Bolinas, CA 94924',
    'Golden Gate View Point, Old Conzelman Rd, Mill Valley, CA',
    'Balboa Ave and 26th Ave, San Francisco, CA',
    'Dimond Slice Pizza, 2208 MacArthur Blvd, Oakland, CA 94602',
    'The Marshall Store, Marshall, CA',
    'Anchor Bay Campground, California 1, Gualala, CA',
    'Ave of the Giants, Scotia, CA',
    'Eureka, CA',
    'Yurok Loop Trail, Klamath, CA 95548',
    'Boy Scout Tree Trailhead, Crescent City, CA 95531',
    'Stout Grove Trailhead, 17 West 4th Avenue, Crescent City, CA 95531',
    'Visitor’s Center, California 95531',
    'SeaQuake Brewing, 400 Front St, Crescent City, CA 95531',
    'Harris Beach State Park, Brookings, OR',
    'Honey Bear by the Sea RV Resort and Campground, ' +
    '34161 Ophir Rd, Gold Beach, OR 97444',
    '87419 Stewart Ln, Bandon, OR 97411',
    'Charleston, OR 97420',
    'Umpqua Lighthouse State Park, Reedsport, OR 97467',
    'Beachside State Park, Waldport, OR 97394',
    'Corvallis, OR',
    'Newport, OR',
    'Pacific City, OR',
    'Netarts, OR',
    'Tillamook, OR',
    'Portland, OR',
    'Roots Wine Company, 19320 NE Woodland Loop Rd, Yamhill, OR 97148',
    'Nehalem Bay State Park, OR',
    'Cannon Beach, OR',
    'Seaside, OR',
    'Astoria, OR',
    'Grayland Beach State Park, Grayland, WA 98547',
    "Grays Harbor Lighthouse, Westport, WA",
    'Aberdeen, WA',
    'Quinault, WA 98575',
    'La Push, WA 98350',
    'Sol Duc Hot Springs Resort, Port Angeles, WA 98363',
    'Tacoma, WA',
    'Olympia, WA',
    'Millersylvania State Park, 12245 Tilley Rd SW, Olympia, WA 98512',
    'Aberdeen, WA',
    'Olympia, WA',
    'Woodinville, WA',
    'Lake Forest Park, WA',
    'Washington Park Arboretum, Arboretum Drive East, Seattle, WA',
    'Lake Forest Park, WA',
    'Queen Anne, Seattle, WA',
    'Issaquah, WA',
    'Squak Mountain, WA 98027',
    'Lake Forest Park, WA',
    'Shoreline, Seattle, WA',
    'Burien, WA',
    'Seatac International Airport, WA',
    'Lake Forest Park, WA',
    'Snoqualmie Falls, WA',
    'Fall City, WA',
    'Steel Wheel Farm, WA',
    'The Blue Heron Golf Course, WA',
    'Tolt River John MacDonald Park, WA',
    'Carnation, WA',
    'Duvall, WA',
    'Cottage Lake, WA',
    'Lake Forest Park, WA',
    'Gold Creek Pond, WA',
    'Lake Forest Park, WA',
    'Fremont Brewing, Seattle, WA',
    'KEXP, Seattle, WA',
    'Seattle Great Wheel, Seattle, WA',
    'Lake Forest Park, WA',
    'Leavenworth, WA',
    'Sun Lakes, Dry Falls State park, WA,',
    'Wilbur, WA',
    'Spokane, WA',
    'Priest River, ID',
    'Sagle, ID',
    'Sandpoint, ID',
    'Sagle, ID',
    'Thompson Falls, MT',
    'Missoula, MT',
    'Jackson Hot Springs, MT',
    'Bozeman Hot Springs, MT',
    'Chico Hot Sprints Resort & Day Spa, Chico Road, Pray, MT',
    'Yellowstone National Park North Entrance, MT',
    'Mammoth Hot Springs Hotel, Yellowstone, WY 82190',
    'Bozeman, MT',
    'Jackson, WY',
    'Taggart Lake Trailhead, Alta, WY 83414',
    'Jackson, WY',
    'Mustang Ridge Campground, Dutch John, UT 84023',
    'Ashley National Forest, US-191, Dutch John, UT 84023',
    'Cub Creek Petroglyphs, Jensen, UT 84035',
    'Cedar campground, Colorado 325, Rifle, CO',
    'Aspen, CO',
    'Fort Collins, CO',
    'Boulder, CO',
    'Cheyenne Mountain State Park, CO',
    'Garden of the Gotds, North 30th St, Colorado Springs, CO',
    'Taos, NM',
    'Black Rock Hot Springs, NM',
    'Taos, NM',
    'Arroyo Seco, NM',
    'Taos, NM',
    'Enchanted Circle Pottery, Taos, NM',
    'Santa Fe, NM',
    'Bandelier National Monument, NM',
    'Rancho Gallina Eco-Retreat, Santa Fe, NM',
    'Los Cerrillos, NM',
    'Madrid, NM',
    'Golden, NM',
    'Las Cruces, NM',
    'White Sands National Monument, NM',
    'Oliver Lee Memorial State Park, NM',
    'Ruidoso, NM',
    'Roswell, NM',
    'Carlsbad Caverns National Park Visitor Center, NM',
    'Guadalupe Mountains National Park, TX',
    'Marfa, TX',
    'Cottonwood Campground, Big Bend National Park, TX',
    'Chisos Basin Visitor Center, Big Bend National Park, TX',
    'Rio Grande Village Visitor Center, Big Bend National Park, TX',
    'Del Rio, TX',
    'San Antonio, TX',
    'New Braunfels, TX',
    'Pecan Grove RV Park, Austin, TX',
    'Dripping Springs, TX',
    'Pecan Grove RV Park, Austin, TX',
    'Surfside Beach, TX',
    'Bolivar Beach, Bolivar Peninsula, TX',
    '1701 Barbecue, 1701 Calder Ave, Beaumont, TX',
    'Cameron Ferry West Landing, 200 Gulf Beach Hwy, Cameron, LA 70631',
    'Hackberry, LA',
    'Lake Charles, LA',
    'Bell City, LA',
    'Lake Arthur, LA',
    'Cypremort Point State Park, LA',
    'Avery Island, LA',
    'Huey P Long Bridge, Bridge City, LA',
    'Lowerline St, New Orleans, LA',
    'Gulf State Park, AL',
    'Topsail Hill State Park, FL'
    'St. George Island, FL',
    'Jacksonville, FL',
    'Savannah, GA',
    'Columbia, SC',
    'Aynor, SC',
    'Galivants Ferry, SC',
    'Fair Bluff, NC 28439',
    'Wilmington, NC',
    'Serenity Point, Topsail Beach, NC',
    'North Topsail Beach, NC',
    'Emerald Isle, NC 28594',
    'Ocracoke Island, NC',
    'Kitty Hawk, NC',
    'Cedar Grove, NC',
    'Chapel Hill, NC',
    'Cedar Grove, NC',
    'Charlotte, NC',
    'Asheville, NC',
    # Blue Ridge Parkway south...
    'Wash Creek Valley Overlook, Blue Ridge Parkway, NC',
    'Stony Bald Overlook, Blue Ridge Parkway, NC',
    'Mills River Valley Overlook, Blue Ridge Parkway, NC',
    'East Fork Overlook, Blue Ridge Parkway, NC',
    'John Rock Overlook, Blue Ridge Parkway, NC',
    'Sam Knob Trailhead, Black Balsam Knob Rd, Canton, NC 28716'
    'Brevard, NC',
    'Asheville, NC',
    # Blue Ridge Parkway north...
    'Haw Creek Valley Overlook, Blue Ridge Parkway, NC',
    'Lane Pinnacle Overlook, Blue Ridge Parkway, NC',
    'Walker Knob Overlook, Blue Ridge Parkway, NC',
    'Walker Knob Overlook, Blue Ridge Parkway, NC',
    '35.830606, -82.116096',  # near wildacres tunnel
    '35.850598, -82.083678',  # near little switzerland tunnel
    'Bear Den Overlook, Blue Ridge Parkway, NC',
    '4682 Blue Ridge Pkwy, Linville, NC 28646'
    '35.971865, -81.939988',  # near linville river
    'Linville Falls Visitor Center, Warrior Ln, Marion, NC',
    'Lost Cove Cliffs Overlook, Blue Ridge Parkway, NC',
    'Little Bald Overlook, Blue Ridge Parkway, NC',
    'Grandfather Mountain Overlook, Blue Ridge Parkway, NC',
    'Blowing Rock, NC',
    'Boone, NC',
    '37.22282107060463, -79.92671615351344',
    'Roanoke River Overlook, Blue Ridge Pkwy, Roanoke, VA 24014',
    '37.328318, -79.856827',
    'Apple Orchard Falls Trailhead, Buchanan, VA',
    'Boston Knob Overlook, Vesuvius, VA',
    'Afton Overlook, Afton, VA 22920',
    'Brown Mountain Overlook, Free Union, VA 22940',
    'Bearfence Mountain Trailhead, Elkton, VA',
    '38.651522, -78.311583',
    'Sperryville, VA',
    'Culpepper, VA',
    'District Heights, MD',
    'Washington, DC',
    'Leesburg, VA',
    'Washington, DC',
    'Fairfax, VA',
    'Falls Church, VA',
    'Baltimore, MD'
]

future = [
    'Baltimore, MD',
    'Bethany Beach, DE',
    'Fins Fish House & Raw Bar, Rehoboth, DE',
    'Manalapan, NJ',
    'New York, NY',
    'Kingston, NY',
    'Providence, RI',
    'Boston, MA',
    'Nashua, NH',
    'Portland, ME',
    'South Brisol, ME',
    'Port Clyde, ME',
    'Quebec City, Quebec, Canada',
    'Montreal, Canada',
    'North Bay, Ontario, Canada',
    'Saulte Ste. Marie, Ontario, Canada',
    'Little Beaver Lake Campground, Burt Township, MI 49884',
    'Milwaukee, WI',
    'Madison, WI',
    'Minneapolis, MN',
    'Madeleine Island, WI',
    'Ashland, WI',
    'Peninsula State Park, WI',
    'Chicago, IL',
    'Indianapolis, IN',
    'Louisville, KY',
    'Nashville, TN',
    'St Louis, MO',
    'Columbia, MO',
    'Kansas City, KS',
    'Cedar Rapids, IA',
    'Watertown, WI',
    'Milwaukee, WI'
]


####
# Re-do with Segments
####
past_route = Route(label='past')
for idx in range(len(past)-1):
    past_route.find_or_create_segment(past[idx], past[idx+1])

future_route = Route(label='future')
for idx in range(len(future)-1):
    future_route.find_or_create_segment(future[idx], future[idx+1])
    print(f"Finished {future[idx]} to {future[idx+1]}")

Route.write_geojson(OUTFILE, [past_route, future_route])
